### ISSUE TITLE
CI: run tests + push to NPM

### ISSUE THREAD

**Issue by jasny** [ltonetwork/lto-crypto#10]
Implement continuous integration via Travis or GitHub actions.

* Run all tests (also for PR).
* Bump version and push to npm

**Comment by brunodb3** [comment]
This package is no longer maintained. It will be deprecated on npm (see #13 ). It's replaced by [`lto-transactions`](https://github.com/ltonetwork/lto-transactions) and [`lto-api.js`](https://github.com/ltonetwork/lto-api.js)
